# Python Pandas I

## Series DataStructure

### Creating series Object

In [116]:
import pandas as sweta

In [117]:
obj1=sweta.Series(range(5))
print(obj1)

0    0
1    1
2    2
3    3
4    4
dtype: int64


In [118]:
obj1=sweta.Series([3.4, 5.0, 6.5, 8.])
print(obj1)

0    3.4
1    5.0
2    6.5
3    8.0
dtype: float64


Example 1 : Write code to create a Series Object using the python sequence [4, 6, 8, 10]. Assume that Pandas
is imported as alias name pd.

In [119]:
import pandas as pd
s1 = pd.Series([4, 6, 8, 10])
# print("Series object 1 :", s1 Not to be used
print("Series Object 1 :")
print(s1)

Series Object 1 :
0     4
1     6
2     8
3    10
dtype: int64


Example 2 : Write a code to create a Series object using the python sequence (11, 21, 31, 41).Assume that pandas is imported as alias name pd.

In [120]:
import pandas as pd
s2 = pd.Series((11,21,31,41))
print(s2)

0    11
1    21
2    31
3    41
dtype: int64


Example 3: Write a code to create a Series object using individual charactors 'o', 'h' and 'o'. Assume that pandas is imported as alias name pd

In [121]:
import pandas as pd
s3 = pd.Series(('o', 'h', 'o'))
print(s3)

0    o
1    h
2    o
dtype: object


Example 4: Write a code to create a Series object using a string: "So funny". Assume that pandas is imported as alias name pd

In [122]:
s4 = pd.Series(("So funny"))
print(s4)

0    So funny
dtype: object


Example 5: Write a code to create a Series object using three different words: "I am laughing".Assume that pandas is imported as alias name pd

In [123]:
s5 = pd.Series(("i", "am", "laughing"))
print(s5)

0           i
1          am
2    laughing
dtype: object


### Specify data as an ndarray

In [124]:
import pandas as pd
import numpy as np
s1 = np.arange(3, 13,3.5)
print(s1)
s2 = pd.Series(s1)
print(s2)

[ 3.   6.5 10. ]
0     3.0
1     6.5
2    10.0
dtype: float64


Example 6: Write a program to create a series object using an ndarray that has 5 elements in the range 24 to 64.

In [125]:
s1 = np.arange(24,64,8)
print(s1)
s2 = pd.Series(s1)
print(s2)

[24 32 40 48 56]
0    24
1    32
2    40
3    48
4    56
dtype: int64


Example 6 II :  Write a program to create a series object using an ndarray that has 5 elements in the range 24 to 64.d
d


In [126]:
s5 = pd.Series(np.linspace(24,64,5))
print(s5)

0    24.0
1    34.0
2    44.0
3    54.0
4    64.0
dtype: float64


Example 7: Write a program to create a series object using an ndarray that is created by tiling a list [3,5],twice.

In [127]:
s3 = pd.Series(np.tile([3,5], 2))
print(s3)

0    3
1    5
2    3
3    5
dtype: int64


In [128]:
s4 = pd.Series({'Jan':31, 'Feb':28,'Mar':31})
print(s4)

Jan    31
Feb    28
Mar    31
dtype: int64


Example 8: Write a program to create a series object using a dictionary that stores the number of students in each section of class 12 in
your school.

In [129]:
sudt = {'A':30, 'B':32, 'C':28, 'D':29}
s = pd.Series(sudt)
print(s)


A    30
B    32
C    28
D    29
dtype: int64


Specify data as a scalar value

In [130]:
medalsWon = pd.Series(10, index = range(0,1))
medal2 = pd.Series(15, index = range(1,6,2))
ser2 = pd.Series('Yet to start', index = ['Indore', 'Delhi', 'Simla'])
print(medalsWon)
print(medal2)
print(ser2)


0    10
dtype: int64
1    15
3    15
5    15
dtype: int64
Indore    Yet to start
Delhi     Yet to start
Simla     Yet to start
dtype: object


Example 9: Write a program to creata a series object that stores the initial budget allocated(50000/- each) for the four quarters of the year: Qtr1, Qtr2, Qtr3, Qtr4.

In [131]:
s1 = pd.Series(50000, index = ['Qtr1','Qtr2','Qtr3','Qtr4'])
print(s1)

Qtr1    50000
Qtr2    50000
Qtr3    50000
Qtr4    50000
dtype: int64


Example 10: Total no. of meadals won is 200 in the Inter University games held every alternate year. Write code to create a series object that stores these medals for games to be held in the decade 2020-
2029.

In [132]:
s1 = pd.Series(200, index = range(2020,2029,2))
print(s1)

2020    200
2022    200
2024    200
2026    200
2028    200
dtype: int64


### Creating Series Objects - Additional Functionality

In [133]:
obj1 = pd.Series([6.5,np.NaN, 2.34])
print(obj1)

0    6.50
1     NaN
2    2.34
dtype: float64


In [134]:
import pandas as pd
arr = [31,28,31,30]
mon = ['Jan','Feb','Mar','Apr']
obj5 = pd.Series(data = arr, index = mon, dtype = np.float64)
print(obj5)
obj2 = pd.Series(data = [32,34,35], index = ['A','B','C'])
print(obj2)
obj3 = pd.Series(arr, index = mon)
s3 = pd.Series(range(1,15,3), index = [x for x in 'abcde'])
print(obj3)
print(s3)

Jan    31.0
Feb    28.0
Mar    31.0
Apr    30.0
dtype: float64
A    32
B    34
C    35
dtype: int64
Jan    31
Feb    28
Mar    31
Apr    30
dtype: int64
a     1
b     4
c     7
d    10
e    13
dtype: int64


Example 11: A python list namely section stores the section names ('A','B','C','D') of class 12 in your schoool. Another contri stores the contribution made by these students to a charity fund endorsed by the school. Write code to create a series object that stores as the values and the section names as the indexes

In [135]:
section = ['A','B','C','D']
contri = [6700,5600,5000,5200]
s11 = pd.Series(data = contri, index = section)
print(s11)

A    6700
B    5600
C    5000
D    5200
dtype: int64


In [136]:
a = np.arange(9,13)
print(a)
s2 = pd.Series(index = a, data = a*2 )
print(s2)
s3 = pd.Series(index = a, data = a**2 )
print(s3)

[ 9 10 11 12]
9     18
10    20
11    22
12    24
dtype: int64
9      81
10    100
11    121
12    144
dtype: int64


In [137]:
lst = [9,10,11,12]
obj8 = pd.Series(data = (2 * lst))
print(obj8)

0     9
1    10
2    11
3    12
4     9
5    10
6    11
7    12
dtype: int64


Example 12: Write a program to creaye a series object that stores the contribution amount as the values and the section names as the indexes with datatype as float32.

In [138]:
import pandas as pd
import numpy as np
section = ['A','B','C','D','E']
contri = np.array([6700,5600,5000,5200,np.NaN])
s12 = pd.Series(data = contri*2, index = section, dtype = np.float32)
print(s12)

A    13400.0
B    11200.0
C    10000.0
D    10400.0
E        NaN
dtype: float32


In [139]:
val = np.arange(2.75,50,9.75)
print(val)
array = ([2.75,12.5,22.25,32.  ,41.75])
ob3 = pd.Series(val, index = ['a','b','a','a','b'])
print(ob3)

[ 2.75 12.5  22.25 32.   41.75]
a     2.75
b    12.50
a    22.25
a    32.00
b    41.75
dtype: float64


Appendix-I

In [140]:
s1 = pd.Series([11,12,13])
print(s1)

0    11
1    12
2    13
dtype: int64


In [141]:
a2 = pd.Series([11.1,12.2,13.3])
print(a2)

0    11.1
1    12.2
2    13.3
dtype: float64


In [142]:
a3 = pd.Series([11,12.2,13.3])
print(a3)

0    11.0
1    12.2
2    13.3
dtype: float64


In [143]:
a4 = pd.Series([11,12.2,13.3, "Hii"])
print(a4)

0      11
1    12.2
2    13.3
3     Hii
dtype: object


In [144]:
obj5 = pd.Series(data = arr, index = mon, dtype = np.float64)
print(obj5)
print(obj5.index)
print(obj5.values)

Jan    31.0
Feb    28.0
Mar    31.0
Apr    30.0
dtype: float64
Index(['Jan', 'Feb', 'Mar', 'Apr'], dtype='object')
[31. 28. 31. 30.]


In [145]:
obj2 = pd.Series([3.5,5.,6.5,8.])
print(obj2)
obj3 = pd.Series([6.5,np.NaN,2.34])
print(obj3)

0    3.5
1    5.0
2    6.5
3    8.0
dtype: float64
0    6.50
1     NaN
2    2.34
dtype: float64


Setting the index name.

In [146]:
ser1 = pd.Series([1,2,3], index = ['a','b','c'])
print(ser1)
ser1.index.name = "NewId"
print(ser1)

a    1
b    2
c    3
dtype: int64
NewId
a    1
b    2
c    3
dtype: int64


Setting Series Name

In [147]:
print(ser1)
ser1.name = "Mys"
print(ser1)
print(ser1.name)

NewId
a    1
b    2
c    3
dtype: int64
NewId
a    1
b    2
c    3
Name: Mys, dtype: int64
Mys


Retrieving Data Type (dtype) and Size of Type(itemsize) and Size

In [148]:
print(obj2.dtype)
print(obj2.size)
print(type(obj2))

print(obj2.shape, obj3.shape)


float64
4
<class 'pandas.core.series.Series'>
(4,) (3,)


Retrieving Dimension (number of axis: ndim attribute)
Size (size attribute) and Number of Bytes (nbytes attribute)

In [149]:
print(obj2.ndim)

1


In [150]:
print(obj2.size, obj3.size)

4 3


In [151]:
print(obj2.nbytes, obj3.nbytes)

32 24


Checking Emptyness (empty attributes) and presence of NaNs (hasnans attribute).

In [152]:
obj1 = pd.Series()
print(obj1.empty)

True


In [153]:
print(obj2.hasnans) # has NaN's

False


In [154]:
print(obj2.count())

4


In [155]:
print(obj3.count())

2


In [156]:
print(len(obj3))

3


Example 13: Consider the two series objects s11 and s12 that you created in example 11 and 12 respectively. Print the attribute od both these objects in a report  form as shown
below.

In [157]:
section = ['A','B','C','D']
contri = [6700,5600,5000,5200]
s14 = pd.Series(data = contri, index = section)
print(s14)
section = ['A','B','C','D','E']
contri = np.array([6700,5600,5000,5200,np.NaN])
s15 = pd.Series(data = contri*2, index = section, dtype = np.float32)
print(s15)
print("Data type (.dtype)      :\t", s14.dtype, '\t\t', s15.dtype)
print("Shape (.shape)          :\t", s14.shape, '\t\t', s15.shape)
print("No. of bytes (.nbytes)  :\t", s14.nbytes, '\t\t', s15.nbytes)
print("No.of dimension (.ndim) :\t", s14.ndim, '\t\t', s15.ndim)
print("Item size (.itemsize)   :\t", s14.size, '\t\t', s15.size)
print("Has NaNs (.hasnans)     :\t", s14.hasnans, '\t\t', s15.hasnans)
print("Empty? (.empty)         :\t", s14.empty, '\t\t', s15.empty)


A    6700
B    5600
C    5000
D    5200
dtype: int64
A    13400.0
B    11200.0
C    10000.0
D    10400.0
E        NaN
dtype: float32
Data type (.dtype)      :	 int64 		 float32
Shape (.shape)          :	 (4,) 		 (5,)
No. of bytes (.nbytes)  :	 32 		 20
No.of dimension (.ndim) :	 1 		 1
Item size (.itemsize)   :	 4 		 5
Has NaNs (.hasnans)     :	 False 		 True
Empty? (.empty)         :	 False 		 False


#### Conda Upgrade :: Ignore



In [3]:
pip install -U %%markdown


/opt/conda/bin/python: No module named pip
Note: you may need to restart the kernel to use updated packages.


In [158]:
pip install -U jedi-language-server


  Using cached jedi-0.19.1-py2.py3-none-any.whl.metadata (22 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 5.2 MB/s eta 0:00:00
Using cached jedi-0.19.1-py2.py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.8/70.8 kB 11.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.0/56.0 kB 5.3 MB/s eta 0:00:00
  Attempting uninstall: jedi
    Found existing installation: jedi 0.18.2
    Uninstalling jedi-0.18.2:
      Successfully uninstalled jedi-0.18.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
python-lsp-server 1.7.1 requires jedi<0.19.0,>=0.17.2, but you have jedi 0.19.1 which is incompatible.
Note: you may need to restart the kernel to use updated packages.


In [159]:
conda install -c conda-forge jedi-language-server


Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 23.9.0
  latest version: 24.3.0

Please update conda by running

    $ conda update -n base -c conda-forge conda

Or to minimize the number of packages updated during conda update use

     conda install conda=24.3.0



## Package Plan ##

  environment location: /opt/conda

  added / updated specs:
    - jedi-language-server


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2024.2.2   |       hbcca054_0         152 KB  conda-forge
    cattrs-23.2.3              |     pyhd8ed1ab_0          46 KB  conda-forge
    certifi-2024.2.2           |     pyhd8ed1ab_0         157 KB  conda-forge
    docstring-to-markdown-0.15 |     pyhd8ed1ab_0          33 KB  conda-forge
    jedi-language-server-0.41.4|     pyhd8ed1ab_0          29 KB  conda-forge
    lsprotocol-2023.0.1        |     py

In [160]:
conda update -n base -c conda-forge conda


Solving environment: done

## Package Plan ##

  environment location: /opt/conda

  added / updated specs:
    - conda


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    alembic-1.13.1             |     pyhd8ed1ab_1         155 KB  conda-forge
    anyio-4.3.0                |     pyhd8ed1ab_0         100 KB  conda-forge
    archspec-0.2.3             |     pyhd8ed1ab_0          48 KB  conda-forge
    asttokens-2.4.1            |     pyhd8ed1ab_0          28 KB  conda-forge
    attrs-23.2.0               |     pyh71513ae_0          53 KB  conda-forge
    babel-2.14.0               |     pyhd8ed1ab_0         7.3 MB  conda-forge
    beautifulsoup4-4.12.3      |     pyha770c72_0         115 KB  conda-forge
    blinker-1.8.0              |     pyhd8ed1ab_0          14 KB  conda-forge
    boltons-24.0.0             |     pyhd8ed1ab_0         291 KB  conda-forge
    bzip2-1.0.8                |

### Accessing a Series object and its elements.


In [ ]:
import pandas as pd
dhirendra = pd.DataFrame(